trabfinal/urls.py
from django.contrib import admin
from django.urls import path
from core.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('login/', login , name='login'),
    path('motos/', motos, name='motos'),
    path('detalhes/<int:id>', detalhes, name='detalhes'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.AdminSite.site_header = 'Sistema da Delegado Motos'
admin.AdminSite.site_title = 'Delegado Motos'
admin.AdminSite.index_title = 'Delegado Motos'

core/models.py
from django.db import models

from json.encoder import INFINITY
from django.db import models

class Base(models.Model):
    criado = models.DateField('Data de criação')
    modificado = models.DateField('Data de atualização: ', auto_now_add=True)
    
    def __str__(self):
        return str(self.criado)


class Imagens(models.Model):
    imagem_sem_fundo = models.ImageField(upload_to='main/', blank=True, null=True, max_length=200)
    imagem_principal = models.ImageField(upload_to='main/', blank=True, null=True, max_length=200)
    imagem1 = models.ImageField(upload_to='main/', blank=True, null=True, max_length=200)
    imagem2 = models.ImageField(upload_to='main/', blank=True, null=True, max_length=200)
    imagem3 = models.ImageField(upload_to='main/', blank=True, null=True, max_length=200)
    imagem4 = models.ImageField(upload_to='main/', blank=True, null=True, max_length=200)
      

class Moto(models.Model):
    modelo = models.CharField(max_length=100)
    marca = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    ano = models.IntegerField()
    cor = models.CharField(max_length=100)
    freio = models.CharField(max_length=100)
    cilindradas = models.CharField(max_length=100)
    quilometragem = models.CharField(max_length=100)
    partida = models.CharField(max_length=100)
    emplacamento = models.CharField(max_length=100)
    descricao = models.TextField()
    imagens = models.ForeignKey(Imagens, on_delete=models.CASCADE)
    base = models.ForeignKey(Base, on_delete=models.CASCADE)
    

core/forms.py
from ast import pattern
from cProfile import label
from dataclasses import field
from email import message
from logging import PlaceHolder
from tkinter import Widget
from unicodedata import name
from django import forms
from django.core.mail.message import EmailMessage

SELECT_CHOICES = (
    ('1', 'Adicionados recentemente'),
    ('2', 'Maior preço'),
    ('3', 'Menor preço') ,
)

class SelectForm(forms.Form):
    selecao = forms.ChoiceField(required=False, choices= SELECT_CHOICES, widget=forms.Select(attrs={'class' : 'form-select form-select-sm row filtro'}), label='')

class CheckboxForm(forms.Form):
    
    #Preço
    ate10 = forms.BooleanField(required=False)
    mais10 = forms.BooleanField(required=False)

    #Marca
    honda = forms.BooleanField(required=False)
    yamaha = forms.BooleanField(required=False)

    #Cilindradas
    c100 = forms.BooleanField(required=False)
    c125 = forms.BooleanField(required=False)
    c150 = forms.BooleanField(required=False)
    c160 = forms.BooleanField(required=False)
    c250 = forms.BooleanField(required=False)
    c300 = forms.BooleanField(required=False)


class ContatoForm(forms.Form):
    nome = forms.CharField(max_length=100, required=True, label='Nome', widget=forms.TextInput(attrs={'class' : ' input-nome'}))
    email = forms.EmailField(max_length=100, label='E-mail', widget=forms.TextInput(attrs={'class' : ' input-email', 'pattern' : '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$'}))
    assunto = forms.CharField( max_length=100, label='Assunto', widget=forms.TextInput(attrs={ 'class' : ''}))
    mensagem = forms.CharField(widget=forms.Textarea(attrs={'class' : ''}), label='Mensagem')

    def send_mail(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        assunto = self.cleaned_data['assunto']
        mensagem = self.cleaned_data['mensagem']

        conteudo = f'Nome:  {nome}\nE-mail: {email}\nAssunto: {assunto}\nMensagem: {mensagem}'

        mail = EmailMessage(
            subject=assunto,
            body=conteudo,
            from_email='contato@seudominio.com.br',
            to=['contato@seudominio',],
            headers={'Reply-to': email}
        )
        mail.send()

class CompraForm(forms.Form):
    nome_completo = forms.CharField(max_length=100,  label='', widget=forms.TextInput(attrs={'placeholder': 'Nome completo', 'class' : 'form-control nome_completo'}))
    email = forms.EmailField(max_length=100, label='', widget=forms.TextInput(attrs={'placeholder': 'E-mail', 'class' : 'form-control', 'pattern' : '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$'}))
    celular = forms.CharField(max_length=15, label='', widget=forms.TextInput(attrs={'placeholder': 'Celular', 'class' : 'form-control','pattern' : '\([0-9]{2}\)[\s][0-9]{5}-[0-9]{4}', 'onkeypress' : 'mascara(this)', }))

    def send_mail(self):
        nome_completo = self.cleaned_data['nome_completo']
        email = self.cleaned_data['email']
        celular = self.cleaned_data['celular']

        conteudo = f'Nome Completo: {nome_completo}\nE-mail: {email}\nCelular: {celular}'

        mail = EmailMessage(
            subject='E-mail enviado a respeito da moto',
            body=conteudo,
            from_email='contato@seudominio.com.br',
            to=['contato@seudominio',],
            headers={'Reply-to': email}
        )
        mail.send()

core/views.py
from django.shortcuts import render

from msilib.schema import ListView
from multiprocessing import context
from re import M, search, template
from unicodedata import decimal
from urllib import request
from django.shortcuts import render
from django.contrib import messages
from core.models import *
from .forms import *
from django.views.generic import ListView
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger
from django.contrib.messages import constants
from django.db.models import Q


def login(request):
    return render(request, 'login.html')

def index(request):
    
    menor_preco = Moto.objects.all().order_by('preco')[:4]
    add_recente = Moto.objects.all().order_by('-id')[:4]

    form = ContatoForm(request.POST or None)

    
    if str(request.method) == 'POST':
        if form.is_valid():
            form.send_mail()
            print("Enviado com sucesso")
            messages.add_message(request, constants.SUCCESS, 'Mensagem enviada com sucesso')
            form = ContatoForm()
        else:
            print("Erro ao enviar email")

    context = {
        'form': form,
        'menor_preco' : menor_preco,
        'add_recente' : add_recente,       
        }

    search = request.GET.get('search')

    if search:
        moto_list = Moto.objects.filter(modelo__icontains=search)
        return render(request, 'motos.html', moto_list)
    return render(request, 'index.html', context)


def motos(request):
    
    #Inicio 
    motos = Moto.objects.all().order_by('-id')
    
    
    cont = 0
    ate10, mais10 = False, False
    honda = False
    yamaha = False
    c100 = False
    c125 = False 
    c150 = False 
    c160 =  False 
    c250 = False 
    c300 = False

    selectform = SelectForm(request.POST or None)
    checkboxform = CheckboxForm(request.POST or None)
    
    #Ver se é um request
    if request.method == "POST":

        #Ver qual dos forms é
        if 'selectBt' in request.POST:
            if selectform.is_valid():
                print('Sucesso')
                resposta = request.POST['selecao']
                if resposta == '1':
                    motos = Moto.objects.all().order_by('-id')
                if resposta == '2':
                    motos = Moto.objects.all().order_by('-preco')
                if resposta == '3':
                    motos = Moto.objects.all().order_by('preco')
        
        if 'checkboxBt' in request.POST:
            if checkboxform.is_valid():
                if request.POST.get("ate10", False):
                    ate10 = True
                    
                if request.POST.get("mais10", False):
                    mais10 = True

                if request.POST.get("honda", False):
                    honda = True
                    
                if request.POST.get("yamaha", False):
                    yamaha = True
                
                if request.POST.get("c100", False):
                    c100 = True
                
                if request.POST.get("c125", False):
                    c125 = True

                if request.POST.get("c150", False):
                    c150 = True
                
                if request.POST.get("c160", False):
                    c160 = True

                if request.POST.get("c250", False):
                    c250 = True

                if request.POST.get("c300", False):
                    c300 = True
                
                
                vetor = [ate10, mais10, honda, yamaha, c100, c125, c150, c160, c250, c300]
                print (f'O vetor é {vetor}')

                cont = vetor.count(True)
                print(cont)
                
                ate10 = Q(preco__lte=10000)
                mais10 = Q(preco__gte=10000)
                honda = Q(marca__icontains='honda')
                yamaha = Q(marca__icontains='yamaha')
                c100 = Q(cilindradas='100')
                c125 = Q(cilindradas='125') 
                c150 = Q(cilindradas='150') 
                c160 =  Q(cilindradas='160') 
                c250 = Q(cilindradas='250')
                c300 = Q(cilindradas='300')
                
                if cont == 1:
                    if request.POST.get("ate10", False):
                        motos = Moto.objects.all().filter(ate10)
                    
                    if request.POST.get("mais10", False):
                        motos = Moto.objects.all().filter(mais10)

                    if request.POST.get("honda", False):
                        motos = Moto.objects.all().filter(honda)

                    if request.POST.get("yamaha", False):
                        motos = Moto.objects.all().filter(yamaha)
                
                    if request.POST.get("c100", False):
                        motos = Moto.objects.all().filter(c100)
                    
                    if request.POST.get("c125", False):
                        motos = Moto.objects.all().filter(c125)

                    if request.POST.get("c150", False):
                        motos = Moto.objects.all().filter(c150)
                
                    if request.POST.get("c160", False):
                        motos = Moto.objects.all().filter(c160)
                
                    if request.POST.get("c250", False):
                        motos = Moto.objects.all().filter(c250)

                    if request.POST.get("c300", False):
                        motos = Moto.objects.all().filter(c300)

                elif cont == 2:
                    print('Duas seleções')
                    
                    # Dois preços 
                    if request.POST.get("ate10", False) and request.POST.get("mais10", False):
                        motos = Moto.objects.all().filter(ate10) | Moto.objects.all().filter(mais10)


                    # Duas marcas
                    if request.POST.get("honda", False) and request.POST.get("yamaha", False):
                        motos = Moto.objects.all().filter(honda) | Moto.objects.all().filter(yamaha)

                    # Duas cilindradas
                    if request.POST.get("c100", False) and request.POST.get("c125", False):
                        motos = Moto.objects.all().filter(c100) | Moto.objects.all().filter(c125)

                    if request.POST.get("c100", False) and request.POST.get("c150", False):
                        motos = Moto.objects.all().filter(c100) | Moto.objects.all().filter(c150)

                    if request.POST.get("c100", False) and request.POST.get("c160", False):
                        motos = Moto.objects.all().filter(c100) | Moto.objects.all().filter(c160)

                    if request.POST.get("c100", False) and request.POST.get("c250", False):
                        motos = Moto.objects.all().filter(c100) | Moto.objects.all().filter(c250)

                    if request.POST.get("c100", False) and request.POST.get("c300", False):
                        motos = Moto.objects.all().filter(c100) | Moto.objects.all().filter(c300)



                    # Um preco e uma marca
                    if request.POST.get("ate10", False) and request.POST.get("honda", False):
                        motos = Moto.objects.all().filter(ate10) & Moto.objects.all().filter(honda)
                    
                    if request.POST.get("ate10", False) and request.POST.get("yamaha", False):
                        motos = Moto.objects.all().filter(ate10) & Moto.objects.all().filter(yamaha)

                    if request.POST.get("mais10", False) and request.POST.get("honda", False):
                        motos = Moto.objects.all().filter(mais10) & Moto.objects.all().filter(honda)
                    
                    if request.POST.get("mais10", False) and request.POST.get("yamaha", False):
                        motos = Moto.objects.all().filter(mais10) & Moto.objects.all().filter(yamaha)

                    # Um preco e uma cilindrada
                    if request.POST.get("ate10", False) and request.POST.get("c100", False):
                        motos = Moto.objects.all().filter(ate10) & Moto.objects.all().filter(c100)
                    
                    if request.POST.get("ate10", False) and request.POST.get("c125", False):
                        motos = Moto.objects.all().filter(ate10) & Moto.objects.all().filter(c125)
                    
                    if request.POST.get("ate10", False) and request.POST.get("c150", False):
                        motos = Moto.objects.all().filter(ate10) & Moto.objects.all().filter(c150)
                    
                    if request.POST.get("ate10", False) and request.POST.get("c160", False):
                        motos = Moto.objects.all().filter(ate10) & Moto.objects.all().filter(c160)
                    
                    if request.POST.get("ate10", False) and request.POST.get("c250", False):
                        motos = Moto.objects.all().filter(ate10) & Moto.objects.all().filter(c250)
                    
                    if request.POST.get("ate10", False) and request.POST.get("c300", False):
                        motos = Moto.objects.all().filter(ate10) & Moto.objects.all().filter(c300)
                    
                    if request.POST.get("mais10", False) and request.POST.get("c100", False):
                        motos = Moto.objects.all().filter(mais10) & Moto.objects.all().filter(c100)
                    
                    if request.POST.get("mais10", False) and request.POST.get("c125", False):
                        motos = Moto.objects.all().filter(mais10) & Moto.objects.all().filter(c125)
                    
                    if request.POST.get("mais10", False) and request.POST.get("c150", False):
                        motos = Moto.objects.all().filter(mais10) & Moto.objects.all().filter(c150)
                    

core/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style_login.scss' %}">
</head>

<body>
   

    <script src="{% static 'js/utils.js'%}"></script>
</body>

</html>

core/templates/motos.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% load mathfilters %}

{% load widget_tweaks %}

{% block title%} Motos {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/style_motos.css' %}"> {% endblock %}

{% block sobre %}{% url 'index' %}#link-sobre{% endblock %}
{% block contato %}{% url 'index' %}#link-contato{% endblock %}

{% block main %}

<main>

  <div class="container-fluid">
    <nav class="row"
      style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
      aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Início</a></li>
        <li class="breadcrumb-item active" aria-current="page">Motos</li>
      </ol>
    </nav>

    <div data-anime="up" class="titulos row">
      <h2>Motos</h2>
    </div>

    <div data-anime="up" class="d-flex justify-content-end">
      <form class="d-flex filtro" action="{% url 'motos' %}" id="myForm" method="post">
        {% csrf_token %}
        {{ selectform }}

        <button name="selectBt" class="btn btn-success" type="submit">Filtrar</button>
      </form>

    </div>


  </div>

  <section data-anime="up" class="container-fluid section-motos">
    <div class="row">

      <div data-anime="left" class="col-xl-2">
        <form class="form-filtro" action="" method="post">
          {% csrf_token %}


          <label class="title-check" for="preco">Preço</label>
          <div class="col-xl-12">
            <div>
              <input class="form-check-input" type="checkbox" name="ate10" id="id_ate10">
              <label for="ate10">Até R$ 10.000,00</label>
            </div>
            <div>
              <input class="form-check-input" type="checkbox" name="mais10" id="id_mais10">
              <label for="mais10">Mais de R$ 10.000,00</label>
            </div>
          </div>
          <hr>


          <label class="title-check" for="marca">Marca</label>
          <div class="col-xl-12">
            <div>
              <input class="form-check-input" type="checkbox" name="honda" id="id_honda">
              <label for="honda">Honda</label>
            </div>

            <div>
              <input class="form-check-input" type="checkbox" name="yamaha" id="id_yamaha">
              <label for="yamaha">Yamaha</label>
            </div>
          </div>
          <hr>

          <label class="title-check" for="cilindradas">Cilindradas</label>
          <div class="col-xl-12">
            <div>
              <input class="form-check-input" type="checkbox" name="c100" id="id_c100">
              <label for="c100">100c</label>
            </div>

            <div>
              <input class="form-check-input" type="checkbox" name="c125" id="id_c125">
              <label for="c125">125c</label>
            </div>

            <div>
              <input class="form-check-input" type="checkbox" name="c150" id="id_c150">
              <label for="c150">150c</label>
            </div>

            <div>
              <input class="form-check-input" type="checkbox" name="c160" id="id_c160">
              <label for="c160">160c</label>
            </div>

            <div>
              <input class="form-check-input" type="checkbox" name="c250" id="id_c250">
              <label for="c250">250c</label>
            </div>

            <div>
              <input class="form-check-input" type="checkbox" name="c300" id="id_c300">
              <label for="c300">300c</label>
            </div>

          </div>
          <hr>
          <div class="col-xl-12">

            <button name="checkboxBt" type="submit" class="btn btn-success bt-buscar">Buscar</button>
          </div>
        </form>
      </div>

      <div class="col-xl-10">

        <section class="container-fluid">
          <div class="row d-flex">
            {% for moto in motos %}
            <div class="cartao col-xl-3 col-lg-4 col-md-4 col-sm-6 col-8">

              <a class="" href="{% url 'detalhes' moto.id %}">
                <div class="card-moto">


                  <p class="marca">{{ moto.marca }}</p>
                  <p class="modelo">{{ moto.modelo }} {{ moto.cilindradas }}c</p>

                  <center>
                    <div class="img-card">

                      <img class="img-fluid" src="/main/{{ moto.imagens.imagem_sem_fundo }}" alt="">

                    </div>
                  </center>

                  <p class="valor">Por R$ {{ moto.preco|intcomma  }}</p>
                  <p class="vista">à vista <span>(com de desconto)</span></p>
                  <p class="prazo">ou 18x de R$ {{ moto.preco|mul:1.025|div:18|floatformat:2 }} com juros</p>


                </div>
              </a>
            </div>
            {% empty %}
            <div class="notfound">
              <div>
                <svg xmlns="http://www.w3.org/2000/svg" shape-rendering="geometricPrecision"
                  text-rendering="geometricPrecision" image-rendering="optimizeQuality" fill-rule="evenodd"
                  clip-rule="evenodd" viewBox="0 0 507 511.92">
                  <path
                    d="M223.36 0c61.68 0 117.53 25 157.95 65.43 40.42 40.42 65.42 96.26 65.42 157.94 0 45.12-13.39 87.13-36.4 122.25L507 450.99l-66.66 60.93-93.23-102.58c-35.42 23.62-77.98 37.39-123.75 37.39-61.67 0-117.52-25-157.94-65.42C25 340.88 0 285.04 0 223.36c0-61.67 25-117.52 65.42-157.94S161.69 0 223.36 0zm59.55 136.89 25.81 25.99-59.78 60.5 59.83 60.56-25.9 25.79-59.48-60.19-59.57 60.3-25.8-25.99 59.77-60.51-59.83-60.56 25.9-25.79 59.48 60.19 59.57-60.29zm80.78-53.84c-35.91-35.91-85.53-58.13-140.33-58.13-54.8 0-104.41 22.22-140.32 58.13-35.91 35.91-58.12 85.51-58.12 140.31s22.21 104.42 58.12 140.32c35.91 35.92 85.52 58.12 140.32 58.12s104.42-22.2 140.33-58.12c35.91-35.9 58.11-85.51 58.11-140.32 0-54.8-22.2-104.4-58.11-140.31z" />
                  </svg>
                <p class="empty">Poxa, nenhuma moto foi encontrada com sua busca. :(</p>
                <p></p>
              </div>
            </div>
            {% endfor %}
          </div>
        </section>

      </div>
    </div>

  </section>
  <div class="container">
    <div class="row ">
      <ul class="pagination justify-content-md-center">

        {% if motos.has_previous %}

        {% if request.GET.search %}
        <li class="page-item">
          <a href="?page={{ motos.previous_page_number }}&search={{ request.GET.search }}"
            class="page-link">Anterior</a>
        </li>
        {% else %}
        <li class="page-item">
          <a href="?page={{ motos.previous_page_number }}" class="page-link">Anterior</a>
        </li>
        {% endif %}


        {% endif %}

        <li class="page-item"><span class="page-link"> Página {{ motos.number }} de
            {{ motos.paginator.num_pages }}</span></li>

        {% if motos.has_next %}

        {% if request.GET.search %}
        <li class="page-item">
          <a class="page-link" href="?page={{ motos.next_page_number }}&search={{ request.GET.search }}">Próximo</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ motos.next_page_number }}">Próximo</a>
        </li>
        {% endif %}

        {% endif %}

      </ul>
    </div>
  </div>






</main>


{% endblock %}

{% block fotsobre %}{% url 'index' %}#link-sobre{% endblock %}
{% block fotcontato %}{% url 'index' %}#link-contato{% endblock %}